name: build-and-test-staging
on:
  push:
    branches:
      #TODO: Needs Change
      - test-actions
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: "3.3.2"
      - run: flutter pub get
      - run: flutter test
      # - run: flutter build ios --release --no-codesign --dart-define=ENVIRONMENT=staging
      - run: flutter build apk --dart-define=ENVIRONMENT=staging
      - run: flutter build appbundle --dart-define=ENVIRONMENT=staging
